package rune:runtime;

// How Rune interfaces with your game :)
interface guest {
  init: func() -> result<_, string>;
  update: func(time: f64, delta-time: f64);
  render: func(time: f64, delta-time: f64);
}

world runtime {
  
  import debug;
  import audio;
  import input;
  import gpu;
  import storage;
  import window;

  export guest;
}
